# Creating Pandas Series Object

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
#pandas series
pd.Series(3.14)


0    3.14
dtype: float64

In [3]:
ser1 = Series([1,2,3,4])
print(ser1)

0    1
1    2
2    3
3    4
dtype: int64


In [4]:
ser2 = Series(['a','b','c','d'])
print(ser2)

0    a
1    b
2    c
3    d
dtype: object


In [5]:
pd.Series(3.14,index=['a','b','c'])

a    3.14
b    3.14
c    3.14
dtype: float64

# Creating Index

In [6]:
var1 = pd.Index(["amjad","khan","pathan","amjuu","aishu","sobha"])

In [7]:
pd.Series([401,420,np.nan,434,425,431],index=var1,name="Amjad")

amjad     401.0
khan      420.0
pathan      NaN
amjuu     434.0
aishu     425.0
sobha     431.0
Name: Amjad, dtype: float64

In [8]:
#dictionaries

In [9]:
d =pd.Series({'john':'emma','edwar':'molly','alex':'iris'},name="amjad")
pd.Series(d)

john      emma
edwar    molly
alex      iris
Name: amjad, dtype: object

In [10]:
d =pd.Series({'john':26,'edwar':24,'alex':30},name="Ages")
print(d)


john     26
edwar    24
alex     30
Name: Ages, dtype: int64


# Data Frames

In [11]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
print(DataFrame(a))

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8


In [13]:
print(DataFrame(a,index=['a','b','c'], columns=['alpha','beta','gama']))

   alpha  beta  gama
a      0     1     2
b      3     4     5
c      6     7     8


In [14]:
#creating from the List-2d
var2 = [(1,'2'),(2,'b'),(3,'c')]
print(DataFrame(var2,index=['a','b','c'],columns=['letters','numbers']))

   letters numbers
a        1       2
b        2       b
c        3       c


In [15]:
print(DataFrame(var2,columns=["numbers","letters"]))

   numbers letters
0        1       2
1        2       b
2        3       c


In [16]:
#Creating from the Dictionaries
print(DataFrame({"numbers":[1,2,3],"letters":['a','b','c']}))

   numbers letters
0        1       a
1        2       b
2        3       c


In [17]:
#what if having one more number higher in the list or tuple?
D = {"numbers":[1,2,3,4],"letters":['am','cx','df']}
D

{'numbers': [1, 2, 3, 4], 'letters': ['am', 'cx', 'df']}

In [18]:
DataFrame({"numbers":ser1,"letters":ser2})

numbers letters
0        1       a
1        2       b
2        3       c
3        4       d

In [19]:
#Numpy python
arr=np.random.randn(5)
pd.Series(arr,index=['h','e','l','l','o'])

h   -0.281678
e   -0.652192
l   -0.795154
l    1.733128
o    0.700477
dtype: float64

# Series Operations

In [20]:
import numpy as np
import pandas as pd
arr=np.random.randn(5)
srs=pd.Series(arr)
print(srs)
srs[1]
srs[:]
srs[2:]
srs[[0,3,4]]
srs*2


0   -0.570757
1    0.777691
2   -0.414412
3   -0.423919
4    0.604830
dtype: float64


0   -1.141514
1    1.555381
2   -0.828824
3   -0.847837
4    1.209661
dtype: float64

# Indexing Pandas

In [21]:
srs = Series(np.arange(5),index=['alpha','beta','gama','delta','epsilon'],name="Names")
srs

alpha      0
beta       1
gama       2
delta      3
epsilon    4
Name: Names, dtype: int32

In [22]:
#selecting boolens
srs[["beta","delta"]]

beta     1
delta    3
Name: Names, dtype: int32

In [23]:
srs["beta":"delta"]

beta     1
gama     2
delta    3
Name: Names, dtype: int32

In [24]:
#Boolen values display
srs>3

alpha      False
beta       False
gama       False
delta      False
epsilon     True
Name: Names, dtype: bool

In [25]:
#Boolen values indicating by position and display data
srs[srs>3]

epsilon    4
Name: Names, dtype: int32

# Indexing:iloc,loc,ix

In [26]:
srs2 = Series(["zeros","ones","twos","three","four"],index=[3,2,4,0,1])
srs2

3    zeros
2     ones
4     twos
0    three
1     four
dtype: object

In [27]:
srs2[2:4]          #It depends upn the Row values

4     twos
0    three
dtype: object

In [28]:
srs2.iloc[2:4]   # It depends upon Index values.It start from "0"

4     twos
0    three
dtype: object

In [29]:
srs2.loc[2:4]   #It depends on the Columns columns,It starts from "1"

2    ones
4    twos
dtype: object

# Creating Data Frame

In [30]:
df = DataFrame(np.arange(21).reshape(7,3),
               columns=["aaa","bbb","ccc"],index=['alpha','beta','gama','delta','epslon','zeta','eta'])

In [31]:
df

aaa  bbb  ccc
alpha     0    1    2
beta      3    4    5
gama      6    7    8
delta     9   10   11
epslon   12   13   14
zeta     15   16   17
eta      18   19   20

In [32]:
df.aaa     # To display column using "dot" notation

alpha      0
beta       3
gama       6
delta      9
epslon    12
zeta      15
eta       18
Name: aaa, dtype: int32

In [33]:
df['aaa']    # To display column by using "LIST" 

alpha      0
beta       3
gama       6
delta      9
epslon    12
zeta      15
eta       18
Name: aaa, dtype: int32

In [34]:
df[['aaa','bbb']]

aaa  bbb
alpha     0    1
beta      3    4
gama      6    7
delta     9   10
epslon   12   13
zeta     15   16
eta      18   19

In [35]:
df.iloc[1:3,1:2]      #It deprnds upon the 'ROWS'  starts from the "0"

bbb
beta    4
gama    7

In [36]:
df.loc['beta':'delta','bbb':'ccc']         #It depends upon the 'COLUMNS'  "1"

bbb  ccc
beta     4    5
gama     7    8
delta   10   11

In [37]:
df

aaa  bbb  ccc
alpha     0    1    2
beta      3    4    5
gama      6    7    8
delta     9   10   11
epslon   12   13   14
zeta     15   16   17
eta      18   19   20

In [38]:
#Mixing
df.iloc[:,1:3].loc[['alpha','gama','zeta']]

bbb  ccc
alpha    1    2
gama     7    8
zeta    16   17

In [39]:
df2 = df.iloc[:,1:3].loc[['alpha','gama','zeta']].copy()
df2           

bbb  ccc
alpha    1    2
gama     7    8
zeta    16   17

In [40]:
df

aaa  bbb  ccc
alpha     0    1    2
beta      3    4    5
gama      6    7    8
delta     9   10   11
epslon   12   13   14
zeta     15   16   17
eta      18   19   20

In [41]:
df.iloc[1,1]=2
df

aaa  bbb  ccc
alpha     0    1    2
beta      3    2    5
gama      6    7    8
delta     9   10   11
epslon   12   13   14
zeta     15   16   17
eta      18   19   20

In [42]:
df2

bbb  ccc
alpha    1    2
gama     7    8
zeta    16   17

In [43]:
df2.iloc[1,1]=3  #Changing the value
df2

bbb  ccc
alpha    1    2
gama     7    3
zeta    16   17

In [44]:
df

aaa  bbb  ccc
alpha     0    1    2
beta      3    2    5
gama      6    7    8
delta     9   10   11
epslon   12   13   14
zeta     15   16   17
eta      18   19   20

In [45]:
df.loc[:,1]=2     # To create an "NEW" column
df

aaa  bbb  ccc  1
alpha     0    1    2  2
beta      3    2    5  2
gama      6    7    8  2
delta     9   10   11  2
epslon   12   13   14  2
zeta     15   16   17  2
eta      18   19   20  2

In [46]:
df2.loc[:,1]=2
df2

bbb  ccc  1
alpha    1    2  2
gama     7    3  2
zeta    16   17  2

* NONE = np.nan

In [47]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

# Random Selecting Number

In [48]:
#selecting random numbers
s.sample(3)

1    3.0
5    8.0
2    5.0
dtype: float64

In [49]:
s.sample(4)

3    NaN
5    8.0
0    1.0
4    6.0
dtype: float64

# If you want to select some percentage from the record

In [50]:
s.sample(frac=0.20)  # It genrates random "Percentage" of a sample data

4    6.0
dtype: float64

In [51]:
s.sample(frac=0.30)

0    1.0
4    6.0
dtype: float64

In [52]:
s.sample(frac=0.50)

3    NaN
2    5.0
0    1.0
dtype: float64

# Masking
* selecting Boolen values

In [53]:
a = pd.Series([1,3,5,np.nan,6,8])
a

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [54]:
#selecting boolen values is nothing but Masing
s==3          # If the value Place in the data set is "True" rather than it displays "False"

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [55]:
s==6

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [56]:
s[s==3]  # To place in a List it creates DataFrame

1    3.0
dtype: float64

In [57]:
s[s>5]

4    6.0
5    8.0
dtype: float64

In [58]:
s[(s>5) &(s<7)]

4    6.0
dtype: float64

 # To find out the missing values

In [59]:
a

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [60]:
a[pd.isnull(a)]  # To display "Null-values" in a DataFrame

3   NaN
dtype: float64

In [61]:
a[~pd.isnull(a)]  # To "Remove" null values column

0    1.0
1    3.0
2    5.0
4    6.0
5    8.0
dtype: float64

In [62]:
srs1 = Series([1,9,-4,3,3])
srs2 = Series([2,3,4,5,10],index=[0,1,2,3,5])

In [63]:
srs1

0    1
1    9
2   -4
3    3
4    3
dtype: int64

In [64]:
srs2

0     2
1     3
2     4
3     5
5    10
dtype: int64

In [65]:
srs1 +srs2

0     3.0
1    12.0
2     0.0
3     8.0
4     NaN
5     NaN
dtype: float64

In [66]:
srs1*srs2

0     2.0
1    27.0
2   -16.0
3    15.0
4     NaN
5     NaN
dtype: float64

In [67]:
srs1**srs2

0      1.0
1    729.0
2    256.0
3    243.0
4      NaN
5      NaN
dtype: float64

In [68]:
#srs1 > srs2

In [69]:
#srs1 < srs2

In [70]:
np.sqrt(srs2)

0    1.414214
1    1.732051
2    2.000000
3    2.236068
5    3.162278
dtype: float64

In [71]:
np.sqrt(abs(srs2))

0    1.414214
1    1.732051
2    2.000000
3    2.236068
5    3.162278
dtype: float64

In [72]:
srs1 

0    1
1    9
2   -4
3    3
4    3
dtype: int64

In [73]:
np.abs(srs1)      # It will convert "Negative" value to postive

0    1
1    9
2    4
3    3
4    3
dtype: int64

In [74]:
srs2

0     2
1     3
2     4
3     5
5    10
dtype: int64

In [75]:
np.abs(srs2)

0     2
1     3
2     4
3     5
5    10
dtype: int64

In [76]:
srs1.mean()

2.4

In [77]:
srs2.std()

3.1144823004794877

In [78]:
srs2.argmax()

4

In [79]:
np.sqrt(srs1)

C:\Users\user\anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)


0    1.000000
1    3.000000
2         NaN
3    1.732051
4    1.732051
dtype: float64

In [80]:
df

aaa  bbb  ccc  1
alpha     0    1    2  2
beta      3    2    5  2
gama      6    7    8  2
delta     9   10   11  2
epslon   12   13   14  2
zeta     15   16   17  2
eta      18   19   20  2

In [81]:
#np.sqrt(df.select_dtype([np.number]))

# creating Geomatric mean

In [82]:
srs

alpha      0
beta       1
gama       2
delta      3
epsilon    4
Name: Names, dtype: int32

In [83]:
#prod():is the product of all elements of like 'srs'

def geomean(srs):
    return srs.prod()**(1/len(srs))

In [84]:
df.apply(geomean)

aaa    0.000000
bbb    6.613338
ccc    8.831059
1      2.000000
dtype: float64

In [85]:
df.apply(geomean,axis='columns')

alpha      0.000000
beta       2.783158
gama       5.091460
delta      6.670621
epslon     8.129628
zeta       9.504353
eta       10.814876
dtype: float64

In [86]:
df.applymap(lambda x:x if x>3 else 3)  # It will convert the data set values below "3"  to "3"

aaa  bbb  ccc  1
alpha     3    3    3  3
beta      3    3    5  3
gama      6    7    8  3
delta     9   10   11  3
epslon   12   13   14  3
zeta     15   16   17  3
eta      18   19   20  3

In [87]:
df

aaa  bbb  ccc  1
alpha     0    1    2  2
beta      3    2    5  2
gama      6    7    8  2
delta     9   10   11  2
epslon   12   13   14  2
zeta     15   16   17  2
eta      18   19   20  2